                exec productRegistration 'Smartphone X10', 'High-performance smartphone with advanced features', '699.99', 'Electronics';
                exec productRegistration 'Classic Denim Jacket', 'Timeless denim jacket for a stylish look', '89.99', 'Clothing';
                exec productRegistration 'Stainless Steel Cookware Set', 'Durable and versatile cookware for your kitchen', '149.99', 'Home and Kitchen';
                exec productRegistration 'Ultra HD LED TV', 'Immersive entertainment experience with stunning visuals', '999.99', 'Electronics';
                exec productRegistration 'Bestselling Novel: "Mystic Shadows"', 'Gripping mystery novel that keeps you on the edge', '19.99', 'Books';
                exec productRegistration 'Cozy Knit Sweater', 'Warm and comfortable knit sweater for chilly days', '49.99', 'Clothing';
                exec productRegistration 'Non-Stick Baking Pan Set', 'Bake your favorite treats easily with these pans', '29.99', 'Home and Kitchen';
                exec productRegistration 'Wireless Noise-Canceling Headphones', 'Enjoy music without distractions with these headphones', '199.99', 'Electronics';
                exec productRegistration 'Language Learning Course: French', 'Comprehensive course to learn French language and culture', '79.99', 'Books';
                exec productRegistration 'Athletic Running Shoes', 'Performance running shoes for your active lifestyle', '119.99', 'Clothing';
                exec productRegistration 'Premium Espresso Machine', 'Brew barista-quality espresso at home with this machine', '299.99', 'Home and Kitchen';
                exec productRegistration 'Gaming Console: NextGen X', 'Experience cutting-edge gaming with the NextGen X console', '499.99', 'Electronics';
                exec productRegistration 'Historical Fiction: "Renaissance Chronicles"', 'Transport yourself to the rich tapestry of the Renaissance era', '24.99', 'Books';
                exec productRegistration 'Business Formal Suit', 'Elegant suit for your professional wardrobe', '249.99', 'Clothing';
                exec productRegistration 'Ceramic Dinnerware Set', 'Elevate your dining experience with this stylish dinnerware set', '89.99', 'Home and Kitchen';
                exec productRegistration 'Smart Fitness Tracker', 'Track your fitness goals and stay motivated', '79.99', 'Electronics';
                exec productRegistration 'Cookbook: "Global Flavors"', 'Explore diverse cuisines with recipes from around the world', '29.99', 'Books';
                exec productRegistration 'Fashionable Sunglasses', 'Protect your eyes while looking stylish in these sunglasses', '39.99', 'Clothing';
                exec productRegistration 'Portable Blender', 'Blend smoothies and shakes on the go with this portable blender', '34.99', 'Home and Kitchen';
                exec productRegistration '4K Action Camera', 'Capture your adventures in stunning 4K resolution', '179.99', 'Electronics';